### PR TITLE
Upgrade Jekyll and dependencies

### PR DESCRIPTION
**Pull request by shawnbot**
The site has some _very_ out-of-date dependencies in the Gemfile. Namely, [Jekyll 0.11.0 is 3.5 years old](https://github.com/jekyll/jekyll/releases/tag/v0.11.0), and that version didn't even _have_ a `serve` command. I removed Liquid from the Gemfile as well because Jekyll has it as a dependency, so it's installed automatically when you run `bundle install`.

Jekyll also complained about the `pygments: true` bit in `_config.yml`, so I updated it to read `highlighter: 'pygments'`.

This means that you can now run `bundle install && bundle exec jekyll serve` and the site will run locally.

### CODE REVIEW

**Comment by gboone** [comment]
:+1: I think you could remove RedCloth from the Gemfile, too, but it looks good!

**Comment by monfresh** [comment]
Is there a particular reason why you specifically chose version 2.4.0? I would either remove the version restriction, or set it to `~> 2.4` so that you can easily get the latest version (which is 2.5.3 by the way) by running `bundle update jekyll`, as opposed to having to hardcode the version number each time.

**Comment by gbinal** [comment]
Please - thank you!

**Comment by monfresh** [comment]
I would also run `bundle update jekyll` one more time to update it to `2.5.3`, the latest version.

**Comment by monfresh** [comment]
:rocket:

**Pull request merged**
