### PR TITLE
Correct api links

### PR DESCRIPTION
**Pull request by Ryandaydev**
Corrects outdated links in issue #57 and #58.

### CODE REVIEW

**Comment by Ryandaydev** [comment]
@saracope this is ready to be merged into the live site. I'm doing this cleanup on the live site before I copy the content over to the redesign.

**Comment by saracope** [comment]
Thanks, @rdgsa! I'm in a block of meetings right now but will try to take a look this afternoon.

**Comment by Ryandaydev** [comment]
Waiting until I get back from vacation.

**Comment by Ryandaydev** [comment]
@saracope please go ahead and merge this into the live site. I'm available to resolve any issues it causes.

**Pull request merged**
